### ISSUE TITLE
output extension is csv, but actually "\t" 

### ISSUE THREAD

**Issue by rsbrennan** [lczech/grenedalf#2]
not very important, but the output of `fst` and `frequency` both have .csv file extensions, but the files are tab delimited.

**Comment by lczech** [comment]
Haha, indeed, that's the default, but both also offer to set the separator char via `--separator-char`. 

Changing the file ending based on that though would seem rather confusing, so I will keep it as `.csv`, independently from which char is actually used. As a matter of fact, I've seen `csv` to stand for "Character Separated Values" at some point as well... less common, but kinda valid ;-)

So, given the above, would you think that comma would be a better default for the `--separator-char` then? I used tab so far, but given that Python and R usually expect csv files to be comma-separated, there is a good argument to change the default.

**Comment by rsbrennan** [comment]
Yes- all very reasonable. I guess default to comma-separated would make a bit more sense. 

will let you know if anything else arises during our analyses. Very easy and nice tool to use so far!

**Comment by lczech** [comment]
Thanks, good to know! I am currently however large restructuring the code, and the command line interface will change in the near future - and offer way more options as well. Hope that won't disrupt your workflow too much then.

Also, I'm changing to comma now - will be part of the next release version then.

**Comment by lczech** [comment]
Hi @rsbrennan,

the change is on the master branch now, and will be part of the next release version 0.2.0, once I've tested the new code more.

Cheer and thanks again for the suggestion
Lucas
