### ISSUE TITLE
Unidentifed issues when creating sync file

### ISSUE THREAD

**Issue by tiphaine-b** [lczech/grenedalf#20]
Hi Lucas,

I'm trying to generate a sync filewith the following command:

grenedalf sync --threads 8 --sam-path /shared/projects/invalbo/tiphaine/results/04_Polishing/Reunion/O_rg_marked_realigned.bam
--sam-path /shared/projects/invalbo/tiphaine/results/04_Polishing/Reunion/P_rg_marked_realigned.bam
--reference-genome-dict-file /shared/projects/invalbo/tiphaine/resources/genomes/AalbF5_filtered.dict
--out-dir /shared/projects/invalbo/tiphaine/results/06_Grenedalf
--multi-file-locus-set intersection --with-header --sam-min-base-qual 30 --sam-min-map-qual 20 --sam-flags-include-any /^0x[1-2]+/
--file-suffix Reunion --filter-region NC_085136.1:1-1000000 --compress --allow-file-overwriting

I have try this option with and without the "--compress" option.

I don't really understand some parts of the error message:

[W::bam_hdr_read] EOF marker is absent. The input is probably truncated

Failed to read BGZF block data at offset 3493214333 expected 20418 bytes; hread returned 0
Read block operation failed with error 4 after 50 of 379 bytes

Do you have a suggestion for the origin of the problem ?
If it comes from my bam files, I don't understant in which way they can be truncated.

Thank you in advance for your help,
Cheers,
Tiphaine

**Comment by lczech** [comment]
Hi Tiphaine @tiphaine-b,

that seems to indicate an issue with your bam files. Grenedalf uses htslib for reading bam files (the same library that samtools is based on), and the error message is coming from there. With which program did you generate those files?

Searching for the error, I found [this](https://github.com/freebayes/freebayes/issues/382) and [this](https://www.seqanswers.com/forum/bioinformatics/bioinformatics-aa/12951-newbie-question-bam_header_read-eof-marker-is-absent?t=15363), which might help you to figure out what is wrong with the files. You can also try [Picard ValidateSamFile](https://gatk.broadinstitute.org/hc/en-us/articles/360036854731-ValidateSamFile-Picard).

Let me know if that helps. As this is an error from htslib, and not grenedalf, there is not very much I can do to fix this, should this turn out to be a deeper issue. But my guess is that the end code mentioned in the above links is missing from your files for some reason.

Cheers and so long
Lucas

**Comment by tiphaine-b** [comment]
Hi again !

Yes you were right, it helps me to find the issue thank you! But not the solving of the problem.
The explanation is probably the compatibility between the library of gatk3  for indel realignement and htslib.
This missing end code error is absent is not reprorted ValidateSamFile anyway...

Cheers
Tiphaine

**Comment by lczech** [comment]
Ah the wonders of bioinformatics file formats... Yeah, it could well be that there is some hiccup between these tools. I found [this](https://www.biostars.org/p/196125/), suggesting to just create the bam file again - maybe that helps. Also [this](https://www.biostars.org/p/305561/) explicitly mentions GATK3 having an issue - please check that it's not that. Alternatively [this](https://www.biostars.org/p/9488537/) hints that it might be due to a header issue.

If neither of the above solves it, I'd suggest to have GATK output sam instead of bam files, and then use samtools to convert to bam later.

Hope that helps, so long
Lucas

**Comment by tiphaine-b** [comment]
Thanks a lot ! 
I'll try to generate bam again, the problem definitely comes from them but where... This is not the GATK3 issue. 

And then, let's have fun with this well-designed tool ! ;) 

Cheers,
Tiphaine

**Comment by lczech** [comment]
> I'll try to generate bam again, the problem definitely comes from them but where... This is not the GATK3 issue.

Okay, then, as said, going via sam, and converting to bam later (for speed and compression) might solve this. Let me know how that goes. If this works, feel free to close this issue.

> And then, let's have fun with this well-designed tool ! ;)

Haha, thanks! I'm currently working on a major update, which will improve the whole windowing, and in particular treatment of missing values and filters, etc. Stay tuned - at the moment, anything related to that will still behave weirdly (see all the other open issues... all have the same underlying cause, to be fixed soon). Also, if you have suggestions for improvements or other types of things you'd like grenedalf to do, let me know! Always looking for inspiration!

Cheers and so long
Lucas

**Comment by tiphaine-b** [comment]
Thanks a lot for your availabilty :) I tried with a little subset of my data and it works ! 

Yes of course, I'll be pleased to contribute within my means as a bioinfo beginner haha

Cheers,
Tiphaine
