### ISSUE TITLE
About pool sequencing population genetic data

### ISSUE THREAD

**Issue by Song-10-YF** [lczech/grenedalf#30]
Hello, I'm a beginner in population genetic data analysis, and I don't quite understand the concept of pool sequencing. For example, I currently have BAM files for multiple populations of a species. Does this count as pool sequencing?

**Comment by lczech** [comment]
Hi @Song-10-YF,

what exactly do you mean by "BAM files for multiple populations of a species"? How were those files produced exactly? Generally, the idea of Pool seq is to sequence genetic material of multiple individuals at the same time, which is a fast and cost efficient way to characterize the genetic features of a whole population (or, to be more precise, of all sequenced individuals). If that is what you did, then yes, that's Pool seq :-)

For some introduction to the topic, see https://doi.org/10.1038/nrg3803 and https://doi.org/10.1038/srep33735

Hope that helps
Lucas

**Comment by lczech** [comment]
Hi @Song-10-YF,

any updates on this?

Cheers
Lucas

**Comment by lczech** [comment]
Hey hey! I assume this is resolved? If not, feel free to re-open or start a new issue :-)
